### ISSUE TITLE
cannot import name 'cached_download' from 'huggingface_hub'

### ISSUE THREAD

**Issue by jakethesnake1126** [ali-vilab/FreeScale#1]
Traceback (most recent call last):
  File "run_freescale.py", line 5, in <module>
    from pipeline_freescale import StableDiffusionXLPipeline
  File "/mnt/ai/FreeScale/pipeline_freescale.py", line 8, in <module>
    from diffusers.image_processor import VaeImageProcessor
  File "/home/jake/anaconda3/envs/freescale/lib/python3.8/site-packages/diffusers/__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "/home/jake/anaconda3/envs/freescale/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 34, in <module>
    from .utils import (
  File "/home/jake/anaconda3/envs/freescale/lib/python3.8/site-packages/diffusers/utils/__init__.py", line 37, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/home/jake/anaconda3/envs/freescale/lib/python3.8/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/home/jake/anaconda3/envs/freescale/lib/python3.8/site-packages/huggingface_hub/__init__.py)

**Comment by arthur-qiu** [comment]
Hi, it should be the problem of the dependency version. Please pull the newest code and it should be solved now. Feel free to let me know if there is still any problem.
